var sourcesIndex = JSON.parse('{\
"aho_corasick":["",[["packed",[["teddy",[],["compile.rs","mod.rs","runtime.rs"]]],["api.rs","mod.rs","pattern.rs","rabinkarp.rs","vector.rs"]]],["ahocorasick.rs","automaton.rs","buffer.rs","byte_frequencies.rs","classes.rs","dfa.rs","error.rs","lib.rs","nfa.rs","prefilter.rs","state_id.rs"]],\
"bitflags":["",[],["lib.rs"]],\
"bitvec":["",[["array",[],["api.rs","iter.rs","ops.rs","traits.rs"]],["boxed",[],["api.rs","iter.rs","ops.rs","traits.rs"]],["field",[],["io.rs"]],["macros",[],["internal.rs"]],["ptr",[],["addr.rs","proxy.rs","range.rs","single.rs","span.rs"]],["slice",[["specialization",[],["lsb0.rs","msb0.rs"]]],["api.rs","iter.rs","ops.rs","specialization.rs","traits.rs"]],["vec",[],["api.rs","iter.rs","ops.rs","traits.rs"]]],["access.rs","array.rs","boxed.rs","devel.rs","domain.rs","field.rs","index.rs","lib.rs","macros.rs","mem.rs","order.rs","ptr.rs","slice.rs","store.rs","vec.rs","view.rs"]],\
"byteorder":["",[],["io.rs","lib.rs"]],\
"c_str_macro":["",[],["c_str.rs"]],\
"cfg_if":["",[],["lib.rs"]],\
"convert_case":["",[],["case.rs","lib.rs","words.rs"]],\
"darling":["",[],["lib.rs","macros_public.rs"]],\
"darling_core":["",[["ast",[],["data.rs","generics.rs","mod.rs"]],["codegen",[],["attr_extractor.rs","default_expr.rs","error.rs","field.rs","from_derive_impl.rs","from_field.rs","from_meta_impl.rs","from_type_param.rs","from_variant_impl.rs","mod.rs","outer_from_impl.rs","trait_impl.rs","variant.rs","variant_data.rs"]],["error",[],["kind.rs","mod.rs"]],["options",[],["core.rs","forward_attrs.rs","from_derive.rs","from_field.rs","from_meta.rs","from_type_param.rs","from_variant.rs","input_field.rs","input_variant.rs","mod.rs","outer_from.rs","shape.rs"]],["usage",[],["generics_ext.rs","ident_set.rs","lifetimes.rs","mod.rs","options.rs","type_params.rs"]],["util",[],["ident_string.rs","ignored.rs","mod.rs","over_ride.rs","path_list.rs","spanned_value.rs","with_original.rs"]]],["derive.rs","from_derive_input.rs","from_field.rs","from_generic_param.rs","from_generics.rs","from_meta.rs","from_type_param.rs","from_variant.rs","lib.rs","macros_private.rs","macros_public.rs"]],\
"darling_macro":["",[],["lib.rs"]],\
"derive_more":["",[],["add_assign_like.rs","add_helpers.rs","add_like.rs","as_mut.rs","as_ref.rs","constructor.rs","deref.rs","deref_mut.rs","display.rs","error.rs","from.rs","from_str.rs","index.rs","index_mut.rs","into.rs","into_iterator.rs","is_variant.rs","lib.rs","mul_assign_like.rs","mul_helpers.rs","mul_like.rs","not_like.rs","parsing.rs","sum_like.rs","try_into.rs","unwrap.rs","utils.rs"]],\
"doc_comment":["",[],["lib.rs"]],\
"downcast_rs":["",[],["lib.rs"]],\
"enumflags2":["",[],["fallible.rs","formatting.rs","lib.rs"]],\
"enumflags2_derive":["",[],["lib.rs"]],\
"env_logger":["",[["filter",[],["mod.rs","regex.rs"]],["fmt",[["humantime",[],["extern_impl.rs","mod.rs"]],["writer",[["termcolor",[],["extern_impl.rs","mod.rs"]]],["atty.rs","mod.rs"]]],["mod.rs"]]],["lib.rs"]],\
"fnv":["",[],["lib.rs"]],\
"funty":["",[],["lib.rs"]],\
"helgoboss_midi":["",[],["bit_util.rs","channel_mod.rs","control_change_14_bit_message.rs","control_change_14_bit_message_scanner.rs","controller_number_mod.rs","key_number_mod.rs","lib.rs","newtype_macros.rs","parameter_number_message.rs","parameter_number_message_scanner.rs","polling_parameter_number_message_scanner.rs","raw_short_message.rs","short_message.rs","short_message_factory.rs","structured_short_message.rs","test_util.rs","u14_mod.rs","u4_mod.rs","u7_mod.rs"]],\
"humantime":["",[],["date.rs","duration.rs","lib.rs","wrapper.rs"]],\
"ident_case":["",[],["lib.rs"]],\
"int_enum":["",[],["error.rs","int.rs","lib.rs"]],\
"int_enum_impl":["",[],["ast.rs","expand.rs","lib.rs","serde.rs","util.rs"]],\
"io_lifetimes":["",[],["example_ffi.rs","lib.rs","portability.rs","raw.rs","traits.rs","views.rs"]],\
"is_terminal":["",[],["lib.rs"]],\
"itoa":["",[],["lib.rs","udiv128.rs"]],\
"libc":["",[["unix",[["linux_like",[["linux",[["arch",[["generic",[],["mod.rs"]]],["mod.rs"]],["gnu",[["b64",[["x86_64",[],["align.rs","mod.rs","not_x32.rs"]]],["mod.rs"]]],["align.rs","mod.rs"]]],["align.rs","mod.rs","non_exhaustive.rs"]]],["mod.rs"]]],["align.rs","mod.rs"]]],["fixed_width_ints.rs","lib.rs","macros.rs"]],\
"libloading":["",[["os",[["unix",[],["consts.rs","mod.rs"]]],["mod.rs"]]],["changelog.rs","error.rs","lib.rs","safe.rs","util.rs"]],\
"linux_raw_sys":["",[["x86_64",[],["errno.rs","general.rs","ioctl.rs"]]],["lib.rs"]],\
"log":["",[],["lib.rs","macros.rs"]],\
"memchr":["",[["memchr",[["x86",[],["avx.rs","mod.rs","sse2.rs"]]],["fallback.rs","iter.rs","mod.rs","naive.rs"]],["memmem",[["prefilter",[["x86",[],["avx.rs","mod.rs","sse.rs"]]],["fallback.rs","genericsimd.rs","mod.rs"]],["x86",[],["avx.rs","mod.rs","sse.rs"]]],["byte_frequencies.rs","genericsimd.rs","mod.rs","rabinkarp.rs","rarebytes.rs","twoway.rs","util.rs","vector.rs"]]],["cow.rs","lib.rs"]],\
"num_enum":["",[],["lib.rs"]],\
"num_enum_derive":["",[],["lib.rs"]],\
"num_traits":["",[["ops",[],["checked.rs","euclid.rs","inv.rs","mod.rs","mul_add.rs","overflowing.rs","saturating.rs","wrapping.rs"]]],["bounds.rs","cast.rs","float.rs","identities.rs","int.rs","lib.rs","macros.rs","pow.rs","real.rs","sign.rs"]],\
"once_cell":["",[],["imp_std.rs","lib.rs","race.rs"]],\
"paste":["",[],["attr.rs","error.rs","lib.rs","segment.rs"]],\
"proc_macro2":["",[],["detection.rs","fallback.rs","lib.rs","marker.rs","parse.rs","rcvec.rs","wrapper.rs"]],\
"proc_macro_crate":["",[],["lib.rs"]],\
"quote":["",[],["ext.rs","format.rs","ident_fragment.rs","lib.rs","runtime.rs","spanned.rs","to_tokens.rs"]],\
"radium":["",[],["lib.rs","macros.rs","types.rs"]],\
"rea_rs":["",[],["audio_accessor.rs","envelope.rs","errors.rs","ext_state.rs","fx.rs","hardware_functions.rs","item.rs","lib.rs","marker.rs","midi.rs","misc_enums.rs","misc_types.rs","project.rs","reaper.rs","send.rs","simple_functions.rs","source.rs","take.rs","track.rs","utils.rs"]],\
"reaper_low":["",[],["bindings.rs","control_surface.rs","lib.rs","macros.rs","midi.rs","pcm_sink.rs","pcm_source.rs","pitch_shift.rs","plugin_context.rs","project_state_context.rs","raw.rs","reaper.rs","reaper_impl.rs","resample.rs","static_context.rs","swell.rs","swell_impl.rs","util.rs"]],\
"reaper_macros":["",[],["lib.rs"]],\
"reaper_medium":["",[],["accelerator_register.rs","audio_hook_register.rs","automation_mode.rs","control_surface.rs","errors.rs","flags.rs","fn_traits.rs","gaccel_register.rs","keeper.rs","key_enums.rs","lib.rs","macros.rs","message_box.rs","midi.rs","misc_enums.rs","misc_newtypes.rs","mutex.rs","pcm_sink.rs","pcm_source.rs","pitch_shift.rs","plugin_context.rs","preview_register.rs","ptr_wrappers.rs","reaper.rs","reaper_pointer.rs","reaper_session.rs","recording_input.rs","resample.rs","string_types.rs","util.rs"]],\
"ref_cast":["",[],["custom.rs","layout.rs","lib.rs","trivial.rs"]],\
"ref_cast_impl":["",[],["lib.rs"]],\
"regex":["",[["literal",[],["imp.rs","mod.rs"]]],["backtrack.rs","compile.rs","dfa.rs","error.rs","exec.rs","expand.rs","find_byte.rs","input.rs","lib.rs","pikevm.rs","pool.rs","prog.rs","re_builder.rs","re_bytes.rs","re_set.rs","re_trait.rs","re_unicode.rs","sparse.rs","utf8.rs"]],\
"regex_syntax":["",[["ast",[],["mod.rs","parse.rs","print.rs","visitor.rs"]],["hir",[["literal",[],["mod.rs"]]],["interval.rs","mod.rs","print.rs","translate.rs","visitor.rs"]],["unicode_tables",[],["mod.rs"]]],["either.rs","error.rs","lib.rs","parser.rs","unicode.rs","utf8.rs"]],\
"rmp":["",[["decode",[],["bytes.rs","dec.rs","ext.rs","mod.rs","sint.rs","str.rs","uint.rs"]],["encode",[],["bin.rs","buffer.rs","dec.rs","ext.rs","map.rs","mod.rs","sint.rs","str.rs","uint.rs","vec.rs"]]],["errors.rs","lib.rs","marker.rs"]],\
"rmp_serde":["",[],["config.rs","decode.rs","encode.rs","lib.rs"]],\
"rustix":["",[["backend",[["linux_raw",[["arch",[["inline",[],["mod.rs","x86_64.rs"]]],["mod.rs"]],["io",[],["epoll.rs","errno.rs","mod.rs","poll_fd.rs","syscalls.rs","types.rs"]],["process",[],["cpu_set.rs","mod.rs","syscalls.rs","types.rs","wait.rs"]],["termios",[],["mod.rs","syscalls.rs","types.rs"]],["time",[],["mod.rs","types.rs"]]],["c.rs","conv.rs","elf.rs","mod.rs","reg.rs"]]]],["ffi",[],["mod.rs"]],["io",[],["close.rs","dup.rs","errno.rs","eventfd.rs","fcntl.rs","ioctl.rs","is_read_write.rs","mod.rs","pipe.rs","poll.rs","read_write.rs","stdio.rs"]],["path",[],["arg.rs","mod.rs"]],["process",[],["chdir.rs","exit.rs","id.rs","kill.rs","membarrier.rs","mod.rs","prctl.rs","priority.rs","rlimit.rs","sched.rs","sched_yield.rs","uname.rs","wait.rs"]],["termios",[],["cf.rs","constants.rs","mod.rs","tc.rs","tty.rs"]]],["const_assert.rs","cstr.rs","lib.rs","utils.rs"]],\
"ryu":["",[["buffer",[],["mod.rs"]],["pretty",[],["exponent.rs","mantissa.rs","mod.rs"]]],["common.rs","d2s.rs","d2s_full_table.rs","d2s_intrinsics.rs","digit_table.rs","f2s.rs","f2s_intrinsics.rs","lib.rs"]],\
"serde":["",[["de",[],["format.rs","ignored_any.rs","impls.rs","mod.rs","seed.rs","utf8.rs","value.rs"]],["private",[],["de.rs","doc.rs","mod.rs","ser.rs","size_hint.rs"]],["ser",[],["fmt.rs","impls.rs","impossible.rs","mod.rs"]]],["integer128.rs","lib.rs","macros.rs"]],\
"serde_derive":["",[["internals",[],["ast.rs","attr.rs","case.rs","check.rs","ctxt.rs","mod.rs","receiver.rs","respan.rs","symbol.rs"]]],["bound.rs","de.rs","dummy.rs","fragment.rs","lib.rs","pretend.rs","ser.rs","this.rs","try.rs"]],\
"serde_json":["",[["features_check",[],["mod.rs"]],["io",[],["mod.rs"]],["value",[],["de.rs","from.rs","index.rs","mod.rs","partial_eq.rs","ser.rs"]]],["de.rs","error.rs","iter.rs","lib.rs","macros.rs","map.rs","number.rs","read.rs","ser.rs"]],\
"strsim":["",[],["lib.rs"]],\
"syn":["",[["gen",[],["clone.rs","debug.rs","eq.rs","gen_helper.rs","hash.rs"]]],["attr.rs","await.rs","bigint.rs","buffer.rs","custom_keyword.rs","custom_punctuation.rs","data.rs","derive.rs","discouraged.rs","drops.rs","error.rs","export.rs","expr.rs","ext.rs","file.rs","generics.rs","group.rs","ident.rs","item.rs","lib.rs","lifetime.rs","lit.rs","lookahead.rs","mac.rs","macros.rs","op.rs","parse.rs","parse_macro_input.rs","parse_quote.rs","pat.rs","path.rs","print.rs","punctuated.rs","reserved.rs","sealed.rs","span.rs","spanned.rs","stmt.rs","thread.rs","token.rs","tt.rs","ty.rs","verbatim.rs","whitespace.rs"]],\
"tap":["",[],["conv.rs","lib.rs","pipe.rs","tap.rs"]],\
"termcolor":["",[],["lib.rs"]],\
"thiserror":["",[],["aserror.rs","display.rs","lib.rs","provide.rs"]],\
"thiserror_impl":["",[],["ast.rs","attr.rs","expand.rs","fmt.rs","generics.rs","lib.rs","prop.rs","valid.rs"]],\
"toml":["",[],["datetime.rs","de.rs","lib.rs","macros.rs","map.rs","ser.rs","spanned.rs","tokens.rs","value.rs"]],\
"unicode_ident":["",[],["lib.rs","tables.rs"]],\
"vst":["",[["util",[],["atomic_float.rs","mod.rs","parameter_transfer.rs"]]],["api.rs","buffer.rs","cache.rs","channels.rs","editor.rs","event.rs","host.rs","interfaces.rs","lib.rs","plugin.rs","prelude.rs"]],\
"wyz":["",[],["bidi.rs","comu.rs","fmt.rs","lib.rs","range.rs"]]\
}');
createSourceSidebar();
